/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Drawer: typeof import('./components/layout/Drawer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Loading: typeof import('./components/layout/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Show: typeof import('./components/layout/Show.vue')['default']
    Toolbar: typeof import('./components/layout/Toolbar.vue')['default']
    View: typeof import('./components/layout/View.vue')['default']
  }
}
